name: Android Build

on: push

jobs:
  build:
    name: "Assemble artifacts"
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: SCM
        uses: actions/checkout@v2
      - name: "Make gradlew executable"
        run: chmod +x ./gradlew

      # Assemble artifacts
      - name: Assemble
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assemble"
