name: CI
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
     # - name: "🧪 Gradle Wrapper Validation"
     #   uses: gradle/wrapper-validation-action@v1
      - name: "🧰 Install JDK"
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          java-package: jdk
      - name: "🧰 Setup Android SDK"
        uses: android-actions/setup-android@v2
      - name: "🦸 Make gradlew executable"
        run: chmod +x ./gradlew
      - name: "🏗 Build"
        run: ./gradlew assembleDebug
      - name: "🧪 Code coverage"
        run: ./gradlew jacocoTestReport
      - name: "📤 Upload code coverage"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: .codecov.yml
      - name: "🧪 Android LINT"
        run: ./gradlew lint
      - name: "🧪 Unit test"
        run: ./gradlew test
